config/routes.rb
Rails.application.routes.draw do

  resources :users,         defaults: {format: :json}
  resource :session,        defaults: {format: :json}

  root to: 'root#root'

  resources :stores,        defaults: {format: :json}
  resources :items,         defaults: {format: :json}
  resources :aisles,        defaults: {format: :json}
  resources :departments,   defaults: {format: :json}
  resources :zones,         defaults: {format: :json}
  resources :cart_items,    defaults: {format: :json}
  resources :carts,         defaults: {format: :json}
  resources :order_items,   defaults: {format: :json}
  resources :orders,        defaults: {format: :json}
  resources :credit_cards,  defaults: {format: :json}
  resources :addresses,     defaults: {format: :json}

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/aisle.rb
class Aisle < ActiveRecord::Base
  belongs_to :department
  has_many :items
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items, source: :item
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :item
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :store
  has_many :aisles, foreign_key: :dept_id
  has_many :items, through: :aisles, source: :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :aisle
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items, source: :item
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :zone
  has_many :departments
  has_many :aisles, through: :departments, source: :aisles
  has_many :items, through: :aisles, source: :items
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true

  before_validation :ensure_session_token

  has_many :addresses
  has_many :credit_cards
  has_many :orders
  has_one :cart

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :stores
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:user_id, :last_four, :type)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/aisles_helper.rb
module AislesHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :last_four %><br>
    <%= f.number_field :last_four %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<h1>Listing credit_cards</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Last four</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.user_id %></td>
        <td><%= credit_card.last_four %></td>
        <td><%= credit_card.type %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New credit_card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @credit_card.user_id %>
</p>

<p>
  <strong>Last four:</strong>
  <%= @credit_card.last_four %>
</p>

<p>
  <strong>Type:</strong>
  <%= @credit_card.type %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>